<?php

/**
 * @file
 */

class contacts {
  /**
   * Build all the URLs for this module.
   */
  function urls() {
    $urls = array();
    
    $urls['contacts'] = array(
      'title' => t('Contacts'),
      'description' => t('Manage all of your contacts'),
      'callback' => 'contacts.contacts_home',
    );

    $urls['contacts/add'] = array(
      'title' => t('Add a contact'),
      'description' => t('Add a new contact'),
      'callback' => 'contacts_add.add_contact',
      'file' => 'contacts_add.php',
    );

    $urls['contacts/view/%'] = array(
      'title' => t('Contacts'),
      'description' => t('Manage all of your contacts'),
      'callback' => 'contacts.contacts_home',
      'type' => 'callback',
    );

    $urls['contacts/view/%'] = array(
      'title' => t('View a contact'),
      'description' => t('Add a new contact'),
      'callback' => 'contacts_add.view_contact',
      'file' => 'contacts_view.php',
      'type' => 'callback',
    );

    $urls['contacts/logout'] = array(
      'title' => t('End Session'),
      'description' => t('Logout'),
      'callback' => 'contacts.logout',
      'type' => 'callback',
    );

    return $urls;
  }

  function contacts_home() 
  {
    $type = node::lookup_type_id('contacts');
    $contacts = node::get_all_of_type($type,15);
    tpl_set('contacts',objectArray($contacts));

    //Check how many other contacts there are in the system excluding the above amount.
    $remaining_contacts = node::count_nodes_of_type($type);
    tpl_set('remaining',objectArray($remaining_contacts));
  }

  function logout()
  {
    unset($_SESSION['SERUM_AUTHENTICATED']);
    header('location:'.base_path());
  }
}
